import Head from 'next/head';
import {useQuery} from "urql";
import {PROCUT_QUERY} from "../lib/query";

import Product from "../components/Products";
import {getTotals} from "../lib/slices/cartItemsSlice";
import {useDispatch} from "react-redux";
import {useEffect} from "react";

export default function Home() {
	
	const dispatch = useDispatch();
	
	useEffect(() => {
		dispatch(getTotals());
	}, [])
	
	//Fetch product data from strapi
	const [results] = useQuery({
		query: PROCUT_QUERY
	});
	const {data, fetching, error} = results;
	
	//Waiting for data
	if(fetching) return <p>Loading..</p>
	//Error msgs
	if(error) return <p>Oh no... {error.message}</p>
	
	//Variables
	const products = data.products.data;
	
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app"/>
				<link rel="icon" href="/favicon.ico"/>
			</Head>
			
			<main>
				<h1>Ahhojkyy</h1>
				<div className="container">
					<div className="product-list">
						{products.map((product, index) => (
							<Product key={index} product={product} />
						))}
					</div>
				</div>
			</main>
		</div>
	)
}
